[project]
name = "three-kingdoms-northern-expeditions-backend"
version = "0.1.0"
dependencies = [
    "fastapi==0.115.8",
    "uvicorn==0.34.0",
    "pydantic==2.11.1",
    "python-dotenv==1.0.1",
    "httpx==0.28.1",
    "jsonschema==4.23.0"
]
requires-python = ">=3.11"
